# use space not tab
apiVersion: apps/v1 # which api to use for deployment
kind: Deployment # pod - service what kind of service/object
# what would you like to call it 
metadata:
  name: mongo-deployment #naming deployment
spec:
  selector: 
    matchLabels:
      app: mongodb #look for this label to match with k8
  replicas: 3
  template:
    metadata:
      labels:
        app: mongodb
    spec: 
      containers:
      - name: mongodb
        image: mutioba/mongo_db:v2 # use the image we built for nginx
        ports:
        - containerPort: 80  