---
apiVersion: v1
kind: Service
metadata: 
  name: mongodb-svc
  namespace: default
spec:
  ports:
  - nodePort: 30004 #range is 30000-32768
    port: 27017
    targetPort: 27017
  selector:
    app: mongodb
  type: NodePort