---
apiVersion: v1
kind: Service
metadata: 
  name: node-svc
  namespace: default
spec:
  ports:
  - nodePort: 30002 #range is 30000-32768
    port: 3000
    targetPort: 3000
  selector:
    app: node
  type: NodePort